/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8i77s9ALZ09
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="w-full max-w-[1200px] mx-auto flex flex-col items-center gap-4 animate-float">
      <div className="w-full h-[500px] bg-white shadow-2xl rounded-3xl aspect-[16/9]" />
      <div className="w-full max-w-lg flex justify-between items-center gap-4 bg-black rounded-3xl p-2">
        <Label className="sr-only" htmlFor="input-field">
          Input Field
        </Label>
        <Input
          className="flex-grow text-white bg-black placeholder-white border-0 rounded-3xl focus:outline-none focus:ring-0 !focus:outline-none"
          id="input-field"
          placeholder="Enter text here"
        />
        <Button className="bg-white text-black p-2 rounded-3xl">
          <svg
            className="h-6 w-6"
            fill="none"
            stroke="currentColor"
            viewBox="0 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M17 8l4 4m0 0l-4 4m4-4H3" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} />
          </svg>
        </Button>
      </div>
    </div>
  )
}
